import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const USAGE = "usage: acceptance-entrypoint-generator <json-ir> <generated-test-output>";

interface Options {
  irPath: string;
  output: string;
}

function fail(message: string, code = 1): never {
  console.error(message);
  process.exit(code);
}

function parseArgs(args: string[]): Options {
  if (args.length !== 2) {
    fail(USAGE, 2);
  }
  return { irPath: args[0], output: args[1] };
}

function metadataName(featureName: string): string {
  const base = featureName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  return `${base}.json`;
}

function relativeToAcceptance(fromFile: string): string {
  const acceptanceDir = path.resolve(process.cwd(), "acceptance");
  const outputDir = path.dirname(path.resolve(fromFile));
  const rel = path.relative(outputDir, acceptanceDir).split(path.sep).join("/");
  return rel === "" ? "." : rel;
}

function generateTestContent(irPath: string, generatedFile: string): string {
  const rel = relativeToAcceptance(generatedFile);
  const irAbsolute = path.resolve(irPath);
  return [
    "// Generated by acceptance-entrypoint-generator. Do not edit.",
    `import { loadFeature, runFeature } from "${rel}/runtime.ts";`,
    `import { createHandlers, makeWorld, disposeWorld } from "${rel}/steps.ts";`,
    "",
    `const irPath = process.env.SWARMFORGE_ACCEPTANCE_IR ?? ${JSON.stringify(irAbsolute)};`,
    "const feature = loadFeature(irPath);",
    "",
    "runFeature(feature, makeWorld, createHandlers(), disposeWorld);",
    "",
  ].join("\n");
}

function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function sourceFeaturePath(featureName: string): string | null {
  const candidate = path.resolve(process.cwd(), "features", `${featureName}.feature`);
  return existsSync(candidate) ? candidate : null;
}

function main(): void {
  const { irPath, output } = parseArgs(process.argv.slice(2));
  if (!existsSync(irPath)) {
    fail(`JSON IR not found: ${irPath}`);
  }
  let feature: { name?: string };
  try {
    feature = JSON.parse(readFileSync(irPath, "utf8"));
  } catch (err) {
    fail(`Failed to parse JSON IR: ${irPath}: ${(err as Error).message}`);
  }
  const featureName = feature.name ?? "feature";
  const generatedDir = output;
  const metaName = metadataName(featureName);
  const generatedFile = path.join(generatedDir, `${metaName.replace(/\.json$/, "")}.test.ts`);
  const content = generateTestContent(irPath, generatedFile);
  mkdirSync(path.dirname(generatedFile), { recursive: true });
  writeFileSync(generatedFile, content);
  const metadata = {
    schema_version: 1,
    feature_path: sourceFeaturePath(featureName) ?? path.resolve(irPath),
    ir_path: path.resolve(irPath),
    implementation_hash: `sha256:${sha256(content)}`,
    hash_scope: "generated_files",
    generated_files: [path.relative(generatedDir, generatedFile)],
  };
  const metaFile = path.join(generatedDir, "metadata", metaName);
  mkdirSync(path.dirname(metaFile), { recursive: true });
  writeFileSync(metaFile, JSON.stringify(metadata, null, 2) + "\n");
  console.log(`Generated ${generatedFile}`);
  console.log(`Metadata ${metaFile}`);
}

main();
